name: Build and Test

on:
  push:
    branches:
      - main
      - dev
      - ci-cd

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn test

  docker_work:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Docker compose
        run: |
          docker network create pastbin-network
          docker-compose up -d

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build . -t pastbin-authentication-service

      - name: Run docker container
        run: docker run -p 8082:8082 --network pastbin-network pastbin-authentication-service
