name: Build and Test

on:
  push:
    branches:
      - main
      - dev
      - ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build project
        run: mvn package -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check Docker functionality
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false