name: Build and Test
on:
  push:
    branches:
      - main
      - dev
      - ci-cd
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: actions/checkout@v3

      - name: Set up Java
        run: actions/setup-java@v3
        with:
          java-version: '17'
  test:
    runs-on: ubuntu-latest
    needs: build
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get repository code
        run: actions/checkout@v3
      - name: Suiiii
        run: echo asd
